### ISSUE TITLE
pls add amnezia

### ISSUE THREAD

**Issue by helpmebro911** [BLUEBL0B/Sing-Box-NGINX-WS#4]
Pls add amnezia wg support.
https://github.com/yury-sannikov/amnezia-wg-docker
https://github.com/amnezia-vpn/

**Comment by BLUEBL0B** [comment]
As far as I know, Amnezia is already very easy to install and use. What do you exactly mean by adding it?

**Comment by helpmebro911** [comment]
Yes. but I don't want to use the official app. it may contain backdoors.
your scripts are more understandable and open.and they have additional settings that the official application does not allow you to make.

**Comment by BLUEBL0B** [comment]
Everything might contain backdoors... But why do you want to use specifically amnezia wg? I guess trojan and vless are more fast and reliable with the correct setup. Also, what country are you from if it's not a secret?

**Comment by helpmebro911** [comment]
according to my tests, amnesia wg is the fastest protocol

**Comment by BLUEBL0B** [comment]
Well, I have seen many complaints about amnezia's speed in their official chat, while Trojan and vless work great for me with just about 5-7% speed loss. And I'm afraid you will have to use amnezia's official app anyway, because you will need a client app which supports amnezia wg

**Comment by helpmebro911** [comment]
pls

**Comment by BLUEBL0B** [comment]
There are significant reasons why I'm not going to add Amnezia:
1) I don't think it's even possible to pass Amnezia through Nginx without ruining the camouflage
2) It's way too different from the technologies used in the script and just won't fit
